[package]
name = "stoppable_thread"
version = "0.1.0"
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]
description = "A wrapper for thread that allows it to be easily stopped cooperatively"

[dependencies]
